"""bq_export - upload finished rollout episodes from intel.db to BigQuery.

At the end of a rollout review (the ladder ended: final stage, exit
criteria, or a governed window - and later again when the outcome label
lands) the episode store's rows for that episode are appended to a
DEDICATED BigQuery dataset. This module performs NO DDL: the dataset,
tables, and views are created out of band by bq/setup-bq.sh from the
committed bq/*.schema.json files, and the exporter only streams rows
into them. The existing harness dataset
(autocloud_analysis.agent_executions) is never touched - its name is
denylisted outright.

Design:
  - Stdlib SQLite reads (no rollout_intel import): the module runs
    anywhere the .db file can be mounted - the Cloud Run event router,
    the agent VM, or a batch job. The store opens read-only and, by
    default, immutable=1 (a mounted quiescent copy): SQLite then
    creates no -wal/-shm coordination files at all. Pass
    immutable=False only when reading a live store that may hold
    unmerged WAL pages. google-cloud-bigquery is imported lazily and
    only for the actual upload.
  - APPEND-ONLY snapshots: every exported row carries exported_at
    (microsecond precision), export_phase ('ladder_complete' |
    'outcome_final' | ...), and export_session. At-least-once delivery
    and the two-phase export produce duplicate snapshots by design;
    analysts read through the *_latest views (LATEST_VIEW_SQL - newest
    snapshot per primary key, outcome_final outranking ladder_complete
    on timestamp ties). Content-hashed row ids let BigQuery's
    short-window best-effort dedupe absorb identical retries without
    ever suppressing a changed snapshot.
  - Torn-snapshot guard: the episodes table is inserted LAST, as the
    commit marker - episodes_latest only advertises a phase once every
    other table's rows for that phase landed. A partial failure raises
    RuntimeError naming what did and did not land; the caller retries
    (re-exporting already-landed tables is harmless snapshot noise).
  - Column names and stored bytes match the SQLite schema exactly -
    a pure 1:1 stream (…_json columns upload as BigQuery JSON,
    timestamps as TIMESTAMP). Join keys (episodes.external_ref /
    event_id, decisions.episode_id) are real store columns stamped at
    write time, never derived here.
  - Scrubbing: pass BOTH hooks or neither - scrub_text(str)->str for
    free-text columns, scrub_json(obj)->obj for parsed *_json values.
    A stored value that is not valid JSON (the recorder never gates)
    is exported as a JSON STRING LITERAL of its scrubbed text - always
    valid for a JSON column, never a poison pill. A scrub_json hook
    that RAISES fails closed for that value (NULL + counted in the
    summary) - unscrubbed structure is never exported by accident.
  - Finished-only by default: NotFinishedError (mid-ladder; callers
    skip it) vs UnknownEpisodeError (ref mismatch; callers must NOT
    treat it as normal - the episode exists under a different ref, or
    the wrong store is mounted). Both subclass LookupError.
  - DDL runs OUT OF BAND: the committed bq/*.schema.json files (the
    `bq mk --schema` format, generated by `python3 bq_export.py
    emit-schemas` and pinned to this module by a parity test) plus
    bq/setup-bq.sh create the dataset, tables, and *_latest views at
    deploy time. A missing table at export time is a setup error and
    says so ("run bq/setup-bq.sh") rather than being retried or
    created on the fly.
"""

from __future__ import annotations

import contextlib
import datetime
import hashlib
import json
import sqlite3
import time
from typing import Any, Callable

DEFAULT_DATASET = "autocloud_rollout_intel"

# Known harness datasets this module must never write to, regardless of
# configuration mistakes.
_DATASET_DENYLIST = {"autocloud_analysis"}

_FINISHED_SQL = ("final_verdict IS NOT NULL "
                 "OR status IN ('awaiting_outcome', 'closed')")

# Backoff schedule for transient streaming-insert failures.
_INSERT_RETRY_SLEEPS = (5, 10, 20)
_RETRIABLE_ROW_REASONS = {"tableUnavailable", "backendError"}


class UnknownEpisodeError(LookupError):
    """No episode row for this id/ref - a correlation mismatch or the
    wrong session store; NOT a normal skip."""


class NotFinishedError(LookupError):
    """The episode's ladder has not ended yet - the normal mid-ladder
    skip for callers that export after every turn."""


# table -> (primary key, ordered columns). Columns mirror
# rollout_intel/models.py byte-for-byte; keep the twins in sync.
_TABLES: dict[str, tuple[str, list[str]]] = {
    "services": ("service_uid", [
        "service_uid", "name", "environment", "region", "runtime",
        "architecture_version", "owner", "aliases_json", "source", "status",
        "confirmed_by", "confirmed_at", "created_at"]),
    "episodes": ("episode_id", [
        "episode_id", "external_ref", "event_id", "service_uid",
        "revision_from", "revision_to", "fingerprint_json",
        "deploy_event_json", "started_at", "status", "final_verdict",
        "final_label", "labeled_at", "architecture_version", "created_at"]),
    "checkpoints": ("checkpoint_id", [
        "checkpoint_id", "episode_id", "stage", "scheduled_at", "session_id",
        "completed_at", "stage_verdict", "policy_status", "policy_version",
        "policy_conflict", "report_version", "report_md", "next_check_at",
        "created_at"]),
    "observations": ("observation_id", [
        "observation_id", "episode_id", "checkpoint_id", "type", "scope_json",
        "observed_at", "fresh_until", "source", "payload_json", "quality_json",
        "content_hash", "sig_verified", "recorded_at"]),
    "decisions": ("decision_id", [
        "decision_id", "checkpoint_id", "episode_id", "kind", "value_json",
        "inputs_json", "recorded_at"]),
    "outcomes": ("outcome_id", [
        "outcome_id", "episode_id", "horizon", "collected_at", "slo_json",
        "rollback_detected", "rollback_at", "incident_refs_json", "source",
        "notes"]),
    "feedback": ("feedback_id", [
        "feedback_id", "episode_id", "type", "actor", "payload_json",
        "recorded_at"]),
    "dossier_journal": ("rev_id", [
        "rev_id", "service_uid", "field", "value_json", "epistemic_type",
        "status", "confidence", "valid_from", "valid_to", "recorded_at",
        "expires_at", "sources_json", "rationale", "owner_verified_by",
        "superseded_by_rev", "memory_id", "activated_at", "deactivated_at"]),
    "retrieval_audit": ("query_id", [
        "query_id", "episode_id", "tool", "filters_json",
        "returned_ids_json", "as_of", "at"]),
}

# Insert order: episodes LAST - its snapshot is the phase's commit
# marker, so episodes_latest never advertises a phase whose other
# tables did not land.
_INSERT_ORDER = [t for t in _TABLES if t != "episodes"] + ["episodes"]

_BQ_TABLE_PREFIX = "rollout_"

_TIMESTAMP_COLS = {
    "confirmed_at", "created_at", "started_at", "labeled_at", "scheduled_at",
    "completed_at", "observed_at", "fresh_until", "recorded_at",
    "collected_at", "rollback_at", "valid_from", "valid_to", "expires_at",
    "activated_at", "deactivated_at", "as_of", "at", "exported_at",
}
_INT_COLS = {"policy_conflict", "report_version", "sig_verified",
             "rollback_detected"}
_FLOAT_COLS = {"confidence"}
# Free-text columns the scrub_text hook covers (…_json columns are
# covered by scrub_json wholesale).
_SCRUB_TEXT_COLS = {"report_md", "notes", "rationale", "actor", "owner",
                    "confirmed_by", "owner_verified_by"}

_EXPORT_COLS = ["exported_at", "export_phase", "export_session"]

# Column documentation, emitted into the *.schema.json files (bq mk
# --schema format) and the created tables. Keyed "table.column" for
# table-specific text, bare "column" for columns shared across tables.
_DESCRIPTIONS = {
    "exported_at": "Snapshot upload time (microsecond precision); the "
                   "*_latest views key on it",
    "export_phase": "ladder_complete (final verdict recorded) | "
                    "outcome_final (re-export after ground-truth labeling)",
    "export_session": "Harness session that ran the export",
    "episode_id": "Episode this row belongs to; ep_<sha256(ref)[:16]> "
                  "for trigger-born episodes",
    "service_uid": "Canonical identity svc://tenant/name/env/region; "
                   "inferred*/ tenants are runtime candidates",
    "services.status": "confirmed (catalog-backed) | candidate (inferred)",
    "episodes.episode_id": "Primary key; deterministic ep_<sha256("
                           "external_ref)[:16]> for trigger-born episodes",
    "episodes.external_ref": "Trigger correlation id: the Cloud Logging "
                             "insertId (or synth-<hash> for insertId-less "
                             "entries). Equals defer_verification's "
                             "unique_id and agent_executions.insert_id - "
                             "THE join key to the harness table. Stamped "
                             "on the episode row at creation",
    "episodes.event_id": "CloudEvents id of the TRIGGERING delivery, when "
                         "the forwarded event carried a top-level 'id'. "
                         "Per-delivery, not per-episode: each deferred fire "
                         "gets a fresh ce-id - find those in "
                         "agent_executions via session_id / insert_id",
    "checkpoints.session_id": "Harness session that most recently armed "
                              "this checkpoint - normally the one that "
                              "recorded it; a crash re-fire overwrites it "
                              "with the new session. Joins "
                              "agent_executions.session_id",
    "episodes.fingerprint_json": "Deterministic rollout fingerprint - the "
                                 "retrieval key for precedent matching",
    "episodes.deploy_event_json": "Parsed deploy event incl. external_ref "
                                  "and trigger provenance (DLP-scrubbed)",
    "episodes.status": "open | in_progress | awaiting_outcome | closed",
    "episodes.final_verdict": "What the agent concluded: healthy | "
                              "regression-suspected | insufficient-evidence",
    "episodes.final_label": "What reality proved: healthy | regressed | "
                            "rolled_back - from outcomes/humans, never from "
                            "agent verdicts",
    "checkpoints.stage": "Policy ladder stage name (policy pack owned)",
    "checkpoints.stage_verdict": "healthy | regression-suspected | "
                                 "insufficient-evidence",
    "checkpoints.policy_status": "Deterministic policy result: pass | fail "
                                 "| insufficient_evidence",
    "checkpoints.report_md": "Full stage report embedding the epistemic "
                             "record (DLP-scrubbed)",
    "checkpoints.next_check_at": "Relative schedule decision '+Nm'; NULL "
                                 "means the ladder ended",
    "checkpoints.report_version": "Monotonic per-episode report version",
    "observations.sig_verified": "1 = HMAC evidence-envelope signature "
                                 "verified at recording time",
    "observations.payload_json": "Observation payload (DLP-scrubbed); may "
                                 "be a JSON string literal when the stored "
                                 "bytes were not parseable",
    "decisions.kind": "stage_verdict | final_verdict | escalation | "
                      "next_check",
    "decisions.episode_id": "Denormalized from the checkpoint at decision "
                            "time so per-episode queries need no join "
                            "(NULL on rows written before the column "
                            "existed; the checkpoint join is authoritative)",
    "outcomes.horizon": "Policy outcome horizon (e.g. 30m/2h/24h) or "
                        "'final'",
    "outcomes.source": "collector | webhook | human",
    "feedback.type": "human_override | human_confirm | incident_link | "
                     "root_cause",
    "dossier_journal.epistemic_type": "approved | observed | asserted | "
                                      "inferred | hypothesized | rejected",
    "dossier_journal.status": "proposed | active | superseded | rejected "
                              "| expired",
    "retrieval_audit.as_of": "Bitemporal read point of the retrieval",
}

LATEST_VIEW_SQL = """-- One view per table: the newest snapshot per primary key.
-- Tiebreakers: outcome_final outranks ladder_complete at equal
-- timestamps; export_session makes the order fully deterministic.
CREATE OR REPLACE VIEW `{project}.{dataset}.{table}_latest` AS
SELECT * EXCEPT (rn) FROM (
  SELECT *, ROW_NUMBER() OVER (
    PARTITION BY {pk}
    ORDER BY exported_at DESC,
             IF(export_phase = 'outcome_final', 1, 0) DESC,
             export_session DESC) AS rn
  FROM `{project}.{dataset}.{table}`)
WHERE rn = 1;
"""


def episode_id_for_ref(ref: str) -> str:
    """Twin of rollout_intel.service.episode_id_for_ref - keep in sync."""
    return f"ep_{hashlib.sha256(ref.encode()).hexdigest()[:16]}"


def _bq_type(col: str) -> str:
    # Legacy type names (INTEGER/FLOAT) deliberately: the conventional
    # vocabulary of `bq mk --schema` files, and what the API echoes
    # back for live tables.
    if col in _TIMESTAMP_COLS:
        return "TIMESTAMP"
    if col in _INT_COLS:
        return "INTEGER"
    if col in _FLOAT_COLS:
        return "FLOAT"
    if col.endswith("_json"):
        return "JSON"
    return "STRING"


def bq_schema(table: str) -> list[dict]:
    """Column schema for one exported table, as plain dicts — the exact
    shape of a `bq mk --schema` JSON file entry, also accepted by
    bigquery.SchemaField.from_api_repr."""
    pk, cols = _TABLES[table]
    fields = []
    for col in cols + _EXPORT_COLS:
        field = {
            "name": col,
            "type": _bq_type(col),
            "mode": ("REQUIRED" if col in (pk, "exported_at") else "NULLABLE"),
        }
        description = _DESCRIPTIONS.get(f"{table}.{col}") or \
            _DESCRIPTIONS.get(col)
        if description:
            field["description"] = description
        fields.append(field)
    return fields


def _ts(value):
    """ISO strings pass through for TIMESTAMP columns; anything
    unparseable becomes NULL rather than failing the row."""
    if value in (None, ""):
        return None
    try:
        datetime.datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return value
    except ValueError:
        return None


def _connect(db_path: str, immutable: bool = True) -> sqlite3.Connection:
    # Read-only; immutable=1 additionally guarantees SQLite creates no
    # -wal/-shm files next to a mounted copy (plain mode=ro may).
    uri = (f"file:{db_path}?immutable=1" if immutable
           else f"file:{db_path}?mode=ro")
    conn = sqlite3.connect(uri, uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def find_finished_episodes(db_path: str, for_phase: str | None = None,
                           immutable: bool = True) -> list[str]:
    """Finished episodes, optionally narrowed to a phase:
    'ladder_complete' -> finished but not yet labeled (what a
    ladder-end fallback should export); 'outcome_final' -> labeled.
    None -> all finished."""
    where = _FINISHED_SQL
    if for_phase == "ladder_complete":
        where = f"({_FINISHED_SQL}) AND final_label IS NULL"
    elif for_phase == "outcome_final":
        where = "final_label IS NOT NULL"
    with contextlib.closing(_connect(db_path, immutable)) as conn:
        rows = conn.execute(
            f"SELECT episode_id FROM episodes WHERE {where} "
            "ORDER BY created_at, episode_id").fetchall()
    return [r["episode_id"] for r in rows]


def collect_episode_rows(db_path: str, episode_id: str, *,
                         force: bool = False,
                         immutable: bool = True) -> dict[str, list[dict]]:
    """All rows belonging to one episode, keyed by (sqlite) table name.

    Raises UnknownEpisodeError when no such episode exists (a ref
    mismatch or wrong store - never a normal skip), NotFinishedError
    (unless force) when its ladder has not ended.
    """
    with contextlib.closing(_connect(db_path, immutable)) as conn:
        episode = conn.execute(
            "SELECT * FROM episodes WHERE episode_id = ?",
            (episode_id,)).fetchone()
        if episode is None:
            raise UnknownEpisodeError(
                f"unknown episode {episode_id!r} on this store - the "
                "correlation ref does not match, or the wrong session "
                "store is mounted")
        finished = conn.execute(
            f"SELECT 1 FROM episodes WHERE episode_id = ? AND ({_FINISHED_SQL})",
            (episode_id,)).fetchone() is not None
        if not (finished or force):
            raise NotFinishedError(
                f"episode {episode_id} has not finished its ladder yet "
                "(no final verdict); pass force=True to export anyway")

        def rows(sql, *args):
            return [dict(r) for r in conn.execute(sql, args).fetchall()]

        # Pure 1:1 stream: every column below is a REAL column in the
        # SQLite store (external_ref/event_id on episodes, episode_id
        # on decisions are stamped at write time) - no export-side
        # derivation or JSON digging. The decisions filter joins via
        # checkpoints only so rows written before the episode_id column
        # existed are still collected; their stored value streams as-is.
        out = {
            "episodes": [dict(episode)],
            "services": rows("SELECT * FROM services WHERE service_uid = ?",
                             episode["service_uid"]),
            "checkpoints": rows(
                "SELECT * FROM checkpoints WHERE episode_id = ? "
                "ORDER BY created_at, checkpoint_id", episode_id),
            "decisions": rows(
                "SELECT d.* FROM decisions d "
                "JOIN checkpoints c ON c.checkpoint_id = d.checkpoint_id "
                "WHERE c.episode_id = ? ORDER BY d.recorded_at, d.decision_id",
                episode_id),
            "observations": rows(
                "SELECT * FROM observations WHERE episode_id = ? "
                "ORDER BY recorded_at, observation_id", episode_id),
            "outcomes": rows(
                "SELECT * FROM outcomes WHERE episode_id = ? "
                "ORDER BY collected_at, outcome_id", episode_id),
            "feedback": rows(
                "SELECT * FROM feedback WHERE episode_id = ? "
                "ORDER BY recorded_at, feedback_id", episode_id),
            "dossier_journal": rows(
                "SELECT * FROM dossier_journal WHERE service_uid = ? "
                "ORDER BY recorded_at, rev_id", episode["service_uid"]),
            "retrieval_audit": rows(
                "SELECT * FROM retrieval_audit WHERE episode_id = ? "
                "ORDER BY at, query_id", episode_id),
        }
    return out


def _prepare(table: str, raw: dict, exported_at: str, phase: str,
             export_session: str,
             scrub_text: Callable[[str], str] | None,
             scrub_json: Callable[[Any], Any] | None,
             stats: dict[str, int]) -> dict:
    pk, cols = _TABLES[table]
    row: dict[str, Any] = {}
    for col in cols:
        value = raw.get(col)
        if value is not None and col in _SCRUB_TEXT_COLS and scrub_text:
            value = scrub_text(str(value))
        if col.endswith("_json"):
            if value is not None:
                try:
                    parsed = json.loads(value)
                except (ValueError, TypeError):
                    # Recorder-never-gates: a stored payload is not
                    # guaranteed parseable. Export the scrubbed text as
                    # a JSON STRING LITERAL - always valid for a JSON
                    # column, never a poison pill.
                    stats["unparseable_json"] = (
                        stats.get("unparseable_json", 0) + 1)
                    text = scrub_text(str(value)) if scrub_text else str(value)
                    value = json.dumps(text)
                else:
                    if scrub_json is not None:
                        try:
                            value = json.dumps(scrub_json(parsed))
                        except Exception:  # noqa: BLE001 - fail CLOSED
                            # The structural scrubber failed on this
                            # value: never export it unscrubbed, never
                            # substitute a weaker scrubber silently.
                            stats["scrub_failures"] = (
                                stats.get("scrub_failures", 0) + 1)
                            print(f"WARNING: scrub_json failed for "
                                  f"{table}.{col} pk={raw.get(pk)!r}; "
                                  "exporting NULL for this value")
                            value = None
            # JSON columns take a JSON-formatted string verbatim.
        elif col in _TIMESTAMP_COLS:
            value = _ts(value)
        row[col] = value
    row["exported_at"] = exported_at
    row["export_phase"] = phase
    row["export_session"] = export_session
    return row


def _row_id(phase: str, pk_value: Any, row: dict) -> str:
    """Content-hashed: identical retries dedupe inside BigQuery's
    best-effort window; a CHANGED same-phase snapshot never does."""
    digest = hashlib.sha256(
        json.dumps(row, sort_keys=True, default=str).encode()
    ).hexdigest()[:12]
    return f"{phase}:{pk_value}:{digest}"


def _check_dataset_name(dataset: str) -> None:
    if dataset in _DATASET_DENYLIST:
        raise ValueError(
            f"dataset {dataset!r} is a harness dataset this exporter must "
            "never write to; use the dedicated dataset "
            f"(default {DEFAULT_DATASET!r})")


def _insert_with_retry(client, table_id: str, rows: list[dict],
                       row_ids: list[str]) -> list:
    """Retry transient streaming-insert failures with backoff. A 404
    (table missing) is NOT retried - DDL runs out of band, so it is a
    setup error and says so. Non-retriable row errors return
    immediately."""
    attempts = (0,) + _INSERT_RETRY_SLEEPS
    errors: list = []
    for i, sleep_s in enumerate(attempts):
        if sleep_s:
            time.sleep(sleep_s)
        try:
            errors = client.insert_rows_json(table_id, rows, row_ids=row_ids)
        except Exception as exc:  # noqa: BLE001 - typed check below
            if type(exc).__name__ == "NotFound":
                raise RuntimeError(
                    f"{table_id} does not exist - the export performs no "
                    "DDL; create the dataset/tables out of band first "
                    "(bq/setup-bq.sh)") from exc
            raise
        if not errors:
            return []
        reasons = {e.get("reason", "") for err in errors
                   for e in (err.get("errors") or [])}
        if not (reasons & _RETRIABLE_ROW_REASONS) or i == len(attempts) - 1:
            return errors
    return errors


def export_episode(db_path: str, *, phase: str,
                   episode_id: str | None = None,
                   external_ref: str | None = None,
                   project: str | None = None,
                   dataset: str = DEFAULT_DATASET,
                   client=None,
                   export_session: str = "",
                   scrub_text: Callable[[str], str] | None = None,
                   scrub_json: Callable[[Any], Any] | None = None,
                   force: bool = False,
                   immutable: bool = True) -> dict:
    """Append one finished episode's rows to the dedicated dataset.

    The dataset and tables MUST exist already — created out of band
    from the committed bq/*.schema.json files (bq/setup-bq.sh); this
    function performs no DDL and a missing table errors with that
    instruction.

    Identify the episode by id or by the trigger correlation ref
    (insertId / deferred unique_id). Returns {table: row_count} plus
    optional 'unparseable_json' / 'scrub_failures' counters.

    Raises NotFinishedError (mid-ladder: skip and try again next turn),
    UnknownEpisodeError (ref mismatch: NOT a normal skip - fall back to
    find_finished_episodes or investigate), RuntimeError when BigQuery
    rejects rows (the message names which tables landed; retrying the
    whole export is safe - duplicates are snapshot noise the *_latest
    views ignore, and the episodes commit marker only lands last).
    """
    _check_dataset_name(dataset)
    if (scrub_text is None) != (scrub_json is None):
        raise ValueError(
            "pass BOTH scrub_text and scrub_json, or neither - one hook "
            "alone leaves either free text or JSON payloads unscrubbed")
    if episode_id is None:
        if not external_ref:
            raise ValueError("pass episode_id or external_ref")
        episode_id = episode_id_for_ref(external_ref)
    collected = collect_episode_rows(db_path, episode_id, force=force,
                                     immutable=immutable)

    if client is None:
        from google.cloud import bigquery
        client = bigquery.Client(project=project)
    project = project or client.project

    exported_at = datetime.datetime.now(
        datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    stats: dict[str, int] = {}
    summary: dict[str, int] = {}
    failures: list[str] = []
    for table in _INSERT_ORDER:
        raw_rows = collected.get(table) or []
        if not raw_rows:
            continue
        pk, _ = _TABLES[table]
        rows = [_prepare(table, r, exported_at, phase, export_session,
                         scrub_text, scrub_json, stats) for r in raw_rows]
        row_ids = [_row_id(phase, r[pk], r) for r in rows]
        table_id = f"{project}.{dataset}.{_BQ_TABLE_PREFIX}{table}"
        errors = _insert_with_retry(client, table_id, rows, row_ids)
        if errors:
            failures.append(f"{table_id}: {errors}")
        else:
            summary[table] = len(rows)
    if failures:
        raise RuntimeError(
            "BigQuery rejected rows: " + "; ".join(failures)
            + f" (tables that DID land this attempt: {summary or 'none'}; "
              "retry the export - the episodes commit marker lands last, "
              "so *_latest never advertises this torn phase)")
    return dict(summary, **stats)


# --- out-of-band DDL artifacts ----------------------------------------------
# The committed bq/*.schema.json files are GENERATED from this module
# (`python3 bq_export.py emit-schemas`) and a parity test pins them to
# bq_schema() - edit the module, regenerate, re-run bq/setup-bq.sh.


def emit_schema_files(outdir: str) -> list[str]:
    """Write one `bq mk --schema` JSON file per table into outdir
    (rollout_<table>.schema.json). Returns the written paths."""
    import os
    os.makedirs(outdir, exist_ok=True)
    written = []
    for table in _TABLES:
        path = os.path.join(outdir, f"{_BQ_TABLE_PREFIX}{table}.schema.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(bq_schema(table), f, indent=2)
            f.write("\n")
        written.append(path)
    return written


def emit_views_sql(project: str, dataset: str = DEFAULT_DATASET) -> str:
    """The *_latest view DDL for every table, as one multi-statement
    script (pipe into `bq query --use_legacy_sql=false`)."""
    return "\n".join(
        LATEST_VIEW_SQL.format(project=project, dataset=dataset,
                               table=f"{_BQ_TABLE_PREFIX}{table}", pk=pk)
        for table, (pk, _) in _TABLES.items())


if __name__ == "__main__":
    import os
    import sys
    usage = ("usage: bq_export.py emit-schemas [OUTDIR] | "
             "emit-views PROJECT [DATASET]")
    if len(sys.argv) >= 2 and sys.argv[1] == "emit-schemas":
        default_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                   "bq")
        outdir = sys.argv[2] if len(sys.argv) > 2 else default_dir
        for written_path in emit_schema_files(outdir):
            print(written_path)
    elif len(sys.argv) >= 3 and sys.argv[1] == "emit-views":
        print(emit_views_sql(sys.argv[2], *(sys.argv[3:4] or ())))
    else:
        print(usage, file=sys.stderr)
        raise SystemExit(2)
